### DISCUSSION TITLE
CompilerError Chainlink-Brownie-Contracts

### DISCUSSION THREAD

**Discussion by oliveruf42** [smartcontractkit/full-blockchain-solidity-course-py#1093] [Q&A] [answered]
Hey guys I'm getting a compiler error due to the Chainlink Contracts. I've changed 
```{} settings.json``` and my brownie config file to @.0.4.0-1.1.1 
I've even tried @2.1.0 and @0.3.0 with no luck. I'm on a Mac and I've tried everything from the Medium article posted here. Any help would be appreciated
>>> Thanks in advance

```
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'
```

```
{
    "solidity.remappings": [
        "@chainlink/=/Users/patrick/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.4.0",
        "@openzeppelin/=/Users/patrick/.brownie/packages/OpenZeppelin/openzeppelin-contracts@4.3.2"
    ]
}
```

```

Compiling contracts...
  Solc version: 0.6.12
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

/Users/eddiebraddock/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.4.0/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol:2:1: ParserError: Source file requires different compiler version (current compiler is 0.6.12+commit.27d51765.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.8.0;
^---------------------^

(env) eddiebraddock@Eddies-iMac smartcontract-lottery % 
```
