### DISCUSSION TITLE
Missing or forbidden. If this issue persists, generate a Github API token and store it as the environment variable `GITHUB_TOKEN`

### DISCUSSION THREAD

**Discussion by ptn77** [smartcontractkit/full-blockchain-solidity-course-py#1112] [Q&A]
Hi,
Here's my brownie-config.yaml:
```YAML
dependencies:
  #-<organization/repo>@<version>
  -smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
```

When I try to compile, I'm getting the error: Missing or forbidden.
If this issue persists, generate a Github API token and store it as the environment variable `GITHUB_TOKEN`
