### DISCUSSION TITLE
Lesson 6: Error at importing chainlink (vscode marks as error)

### DISCUSSION THREAD

**Discussion by cromewar** [smartcontractkit/full-blockchain-solidity-course-py#126] [Q&A] [answered]
I'm running the project on WSL2 Ubuntu 20.04 in a Windows 10 host machine.

On FundMe.sol I have:

```Solidity

// SPDX-License-Identifier: MIT

pragma solidity ^0.6.6;

import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import "@chainlink/contracts/src/v0.6/vendor/SafeMathChainlink.sol";
```

and in brownie-config.yaml 
```YAML
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
```

When I run "brownie compile", the project compiles properly without any problems. However VScode still showing it as an error:

![image](https://user-images.githubusercontent.com/20199180/135645524-ff42a3f1-6c4d-43f8-8e6d-f21f06ec279a.png)

I have no idea why this is happening, I also read info in another post like this one: https://stackoverflow.com/questions/67314540/vscode-solidity-extension-not-finding-openzepplin-imports without any luck, could anyone help me plz?
