### DISCUSSION TITLE
Lesson 9 ParserError: Source "@openzeppelin/contracts/token/ERC20/ERC20.sol" not found

### DISCUSSION THREAD

**Discussion by NewCoderrrrr** [smartcontractkit/full-blockchain-solidity-course-py#1286] [Q&A] [answered]
I copied the exact code from the GitHub. Not using GitHub Repo commands but just copying and pasting and I am getting this error: 
Brownie v1.18.1 - Python development framework for Ethereum

Compiling contracts...
  Solc version: 0.8.12
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

ParserError: Source "@openzeppelin/contracts/token/ERC20/ERC20.sol" not found: File not found. Searched the following locations: "".
 --> contracts/OurToken.sol:5:1:
  |
5 | import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Any ideas on how to fix this?

Under Contracts: OurToken.sol
``` solidity
// contracts/OurToken.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract OurToken is ERC20 {
    // wei
    constructor(uint256 initialSupply) ERC20("OurToken", "OT") {
        _mint(msg.sender, initialSupply);
    }
}

```

Under Scripts: __init__.py 
Nothing in here

Under Scripts: 1_deploy_token.py
```python
from brownie import OurToken
from scripts.helpful_scripts import get_account
from web3 import Web3

initial_supply = Web3.toWei(1000, "ether")


def main():
    account = get_account()
    our_token = OurToken.deploy(initial_supply, {"from": account})
    print(our_token.name())

```
.env 
My own code

.gitattributes
```
*.sol linguist-language=Solidity
*.vy linguist-language=Python

```

.gitignore

```
__pycache__
.env
.history
.hypothesis/
build/
reports/

```
brownie-config.yaml 
``` yaml
dependencies:
 - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
 solc:
  remappings:
    - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
```

requirements.txt

``` txt
eth-brownie
python-dotenv

```
