### DISCUSSION TITLE
KeyError 'eth_usd_price_feed'

### DISCUSSION THREAD

**Discussion by JohnEMagee** [smartcontractkit/full-blockchain-solidity-course-py#1293] [Q&A] [answered]
My deployment is erroring out on `contract_address = config["networks"][network.show_active()][contract_name]` with KeyError 'eth_usd_price_feed'

I went through my helpful_scripts.py and found all the typos I could see:
```
from brownie import (
    network,
    config,
    accounts,
    Contract,
    MockV3Aggregator,
    VRFCoordinatorV2Mock,
    LinkToken,
)

FORKED_LOCAL_ENVIRONMENTS = ["mainnet-fork", "mainnet-fork-dev"]
LOCAL_BLOCKCHAIN_ENVIRONMENT = ["development", "ganache-local"]


def get_account(index=None, id=None):

    if index:
        return accounts[index]
    if id:
        return accounts.load(id)
    if (
        network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENT
        or network.show_active() in FORKED_LOCAL_ENVIRONMENTS
    ):
        return accounts[0]

    return accounts.add(config["wallets"]["from_key"])


contract_to_mock = {
    "eth_usd_price_feed": MockV3Aggregator,
    "vrf_coordinator": VRFCoordinatorV2Mock,
    "link_token": LinkToken,
}


def get_contract(contract_name):
    """This function will grab the contract addreses from the brownie config if defined, otherwise it will deploy a mock version of that ocntract, and return that mock contract.

    Args:
        contract_name (string)

    Returns:
        brownie.network.ProjectContract: THe most recently deployed version of this contract.[-1]
    """
    contract_type = contract_to_mock[contract_name]
    if network.show_active in LOCAL_BLOCKCHAIN_ENVIRONMENT:
        if len(contract_type) <= 0:
            deploy_mocks()
        contract = contract_type[-1]
    else:
        contract_address = config["networks"][network.show_active()][contract_name]
        # address
        # ABI
        contract = Contract.from_abi(
            contract_type._name, contract_address, contract_type.abi
        )
    return contract


DECIMALS = 8
INITAL_VALUE = 200000000000


def deploy_mocks(decimals=DECIMALS, initial_value=INITAL_VALUE):
    account = get_account()
    MockV3Aggregator.deploy(decimals, initial_value, {"from": account})
    link_token = LinkToken.depoloy({"from": account})
    VRFCoordinatorV2Mock.deploy(link_token.address, {"from": account})
    print("Deployed!")
```

Here is my brownie-config.yml (did I miss the development eth_usd_price_feed?  I don't think we need one for development right)

```
dependencies:
  - 'smartcontractkit/chainlink-brownie-contracts@0.4.0'
  - 'OpenZeppelin/openzeppelin-contracts@4.5.0'
compiler:
  solc:
    remappings:
       - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'
       - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
networks:
  default: development
  development:
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    fee: 100000000000000000
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
  rinkeby:
    vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    fee: 100000000000000000
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
```

And for completeness here is my deploy file...
```
from scripts.helpful_scripts import get_account, get_contract
from brownie import Lottery, network, config


def deploy_lottery():
    account = get_account()
    lottery = Lottery.deploy(
        get_contract("eth_usd_price_feed").address,
        get_contract("vrf_coordinator").address,
        get_contract("link_token").address,
        config["networks"][network.show_active()]["fee"],
        config["networks"][network.show_active()]["keyhash"],
        {"from": account},
        publish_source=config["networks"][network.show_active()].get("verify", False),
    )
    print("Deployed Lottery!")


def main():
    deploy_lottery()
```

I realize it's probably a typo somewhere I just cna't find it...thanks in advance
