### DISCUSSION TITLE
Lesson 6: So my project did compile, however, I am still getting the Source error when importing @Chainlink.

### DISCUSSION THREAD

**Discussion by yarg119** [smartcontractkit/full-blockchain-solidity-course-py#1294] [Q&A]
Error: `Source "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol" not found: File import callback not supported`
So this is an error message that everyone gets when they follow the Lesson 6 tutorial, however, mine did not go away after I added my remapping to brownie-config.yaml
```
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
```
I do not know what the issue is as I am on version 0.6.6 Solidity both in my compiler and in my code, and I am using all of the same versions of the packages that Patrick used. I find it even more peculiar that my code compiles and downloads correctly. Is this just something that I should ignore and move on from?
