### DISCUSSION TITLE
Lesson 7: ImportError: cannot import name 'VRFCoordinatorMock' from 'brownie'

### DISCUSSION THREAD

**Discussion by EzeCerino** [smartcontractkit/full-blockchain-solidity-course-py#1303] [Q&A] [answered]
Hello, I am having an error under Lesson 7. The thing is that I can import MockV3Aggregator but I can not import VRFCoordinatorMock or LinkToken. One thing that I have noted is that if I switch the order under the "from brownie import", putting LInkToken before the VRFCoordinatorMock is that one that trougth the error. 

This image is for you to show the .json structure and the folder structure.

![image](https://user-images.githubusercontent.com/95625362/159122321-ed556ff2-b4ad-4c30-9e17-69d64278ce78.png)

This is Helpful Scripts code:

```Python
from brownie import (
      network,
      accounts,
      config,
      Contract,
      MockV3Aggregator,
      VRFCoordinatorMock,
      LinkToken,
  )
  
  FORKED_LOCAL_ENVIROMENTS = ["mainnet-fork", "mainnet-fork-dev"]
  LOCAL_BLOCKCHAIN_ENVIROMENTES = ["development", "ganache-local"]
  
  
  def get_account(index=None, id=None):
      if index:
          return accounts[index]
      if id:
          return accounts.load[id]
      if (
          network.show_active() in LOCAL_BLOCKCHAIN_ENVIROMENTES
          or network.show_active() in FORKED_LOCAL_ENVIROMENTS
      ):
          return accounts[0]
      return accounts.add(config["wallets"]["from_key"])
  
  
  contract_to_mock = {
      "eth_usd_price_feed": MockV3Aggregator,
      "vrf_coordinator": VRFCoordinatorMock,
      "link_token": LinkToken,
  }
  
  
  def get_contract(contract_name):
      """This function will grab the contract addresses from the brownie config
      if defined, otherwhise, it will deploy a mock version of that contract, and
      return the mock contract.
          Arg:
              contract_name (string)
  
          Returns:
              brownie.network.contract.ProjectContracts: The most recently deployed
              version of this contract
      """
      contract_type = contract_to_mock[contract_name]
      if network.show_active() in LOCAL_BLOCKCHAIN_ENVIROMENTES:
          if len(contract_type) <= 0:
              deploy_mocks()
          contract = contract_type[-1]
      else:
          contract_address = config["networks"][network.show_active()][contract_name]
          contract = Contract.from_abi(
              contract_type._name, contract_address, contract_type.abi
          )
      return contract
  
  
  DECIMALS = 8
  STARTING_PRICE = 2000000000
  
  
  def deploy_mocks(decimals=DECIMALS, initial_value=STARTING_PRICE):
      account = get_account()
      MockV3Aggregator.deploy(decimals, initial_value, {"from": account})
      link_token = LinkToken.deploy({"from": account})
      VRFCoordinatorMock.deploy(link_token.address, {"from": account})
      print("Mocks Deployed")

```

This one is deploy_lottery script:

```Python
from scripts.helpful_scripts import get_account, get_contract
from brownie import Lottery, network, config


def deploy_lottery():
    account = get_account(id="myaccount")
    lottery = Lottery.deploy(
        get_contract("eth_usd_price_feed").address,
        get_contract("vrf_coordinator").address,
        get_contract("link_token").address,
        config["networks"][network.show_active()]["fee"],
        config["networks"][network.show_active()]["keyhash"],
        {"from": account},
        publish_source=config["networks"][network.show_activeU()].get("verify", False),
    )
    print("lottery Deplyed!!")


def main():
    deploy_lottery()
```

This is the Lottery.sol file. All other mock codes has been copied from the course folder. 
```

//SPDX-License-Identifier: MIT
pragma solidity ^0.6.6;
import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@chainlink/contracts/src/v0.6/VRFConsumerBase.sol";

contract Lottery is VRFConsumerBase, Ownable {
    address payable[] public players;
    address payable public recentWinner;
    uint256 randomness;
    uint256 public usdEntryFee;
    AggregatorV3Interface internal ethUsdPriceFeed;
    enum LOTTERY_STATE {
        OPEN,
        CLOSED,
        CALCULATING_WINNER
    }
    LOTTERY_STATE public lottery_state;
    uint256 public fee;
    bytes32 keyhash;

    constructor(
        address _priceFeedAddress,
        address _vrfCoordinator,
        address _link,
        uint256 _fee,
        bytes32 _keyhash
    ) public VRFConsumerBase(_vrfCoordinator, _link) {
        usdEntryFee = 50 * (10**18);
        ethUsdPriceFeed = AggregatorV3Interface(_priceFeedAddress);
        lottery_state = LOTTERY_STATE.CLOSED;
        fee = _fee;
        keyhash = _keyhash;
    }

    function enter() public payable {
        //$50 minumun
        require(lottery_state == LOTTERY_STATE.OPEN);
        require(msg.value >= getEntranceFee(), "not enougth eth");
        players.push(msg.sender);
    }

    function getEntranceFee() public view returns (uint256) {
        //
        (, int256 price, , , ) = ethUsdPriceFeed.latestRoundData();
        uint256 adjustedPrice = uint256(price) * 10**10; //18 decimals
        uint256 costToEnter = (usdEntryFee * 10**18) / adjustedPrice;
        return costToEnter;
        //
    }

    function startLottery() public onlyOwner {
        require(
            lottery_state == LOTTERY_STATE.CLOSED,
            "can't start lottery yet!"
        );
        lottery_state = LOTTERY_STATE.OPEN;
    }

    function endLottery() public onlyOwner {
        lottery_state = LOTTERY_STATE.CALCULATING_WINNER;
        bytes32 requestId = requestRandomness(keyhash, fee);
    }

    function fulfillRandomness(bytes32 requestID, uint256 _ramdomness)
        internal
        override
    {
        require(
            lottery_state == LOTTERY_STATE.CALCULATING_WINNER,
            "You are not there yet!"
        );
        require(_ramdomness > 0, "Ramdom not found");
        uint256 indexOfWinner = _ramdomness % players.length;
        recentWinner = players[indexOfWinner];
        recentWinner.transfer(address(this).balance);
        players = new address payable[](0);
        lottery_state = LOTTERY_STATE.CLOSED;
        randomness = _ramdomness;
    }
}
```

I tried:
 - Deleting build folder and brownie compile --all
 - Copied mocks from github folders matching the same solidity compiler versions from the video.
 - deploy mocks with a deploy_mock.py that calls deploy_mocks function
 - Tried moving all mock contracts to different locations, I mean outside the test folder and inside that folder.

I'll copy also my config.yaml file in case there is something that I'm missing. 
```
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
networks:
  default: development
  development:
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    fee: 250000000000000000
  rinkeby:
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    eth_usd_price_feed: '0x78F9e60608bF48a1155b4B2A5e31F32318a1d85F'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    fee: 250000000000000000
    verify: True
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
wallets:
  from_key: ${PRIVATE_KEY}
```
