### DISCUSSION TITLE
Lesson 6 - ValueError: Unknown URI  - must be a path to an IPC socket, a websocket beginning with 'ws' or a URL beginning with 'http'

### DISCUSSION THREAD

**Discussion by wilonweb** [smartcontractkit/full-blockchain-solidity-course-py#1360] [Q&A] [answered]
Hello
When i launch the command `brownie run scripts/deploy.py --network ganache-local`
I got this output 
```
Brownie v1.17.2 - Python development framework for Ethereum

BrownieFundMeProject is the active project.
  File "C:\Users\wilfr\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\_cli\__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "C:\Users\wilfr\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\_cli\run.py", line 44, in main
    network.connect(CONFIG.argv["network"])
  File "C:\Users\wilfr\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\main.py", 
line 40, in connect
    web3.connect(host, active.get("timeout", 30))
  File "C:\Users\wilfr\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\web3.py", 
line 66, in connect
    raise ValueError(
ValueError: Unknown URI - must be a path to an IPC socket, a websocket beginning with 'ws' or a URL beginning with 'http'
```

helpful_scripts.py 
```Python
from brownie import network, config, accounts, MockV3Aggregator
from web3 import Web3

LOCAL_BLOCKCHAIN_ENVIRONMENTS = ["development", "ganache-local"]

DECIMALS = 18
STARTING_PRICE = 2000


def get_account():
    if network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        return accounts[0]
    else:
        return accounts.add(config["wallets"]["from_key"])


def deploy_mocks():
    print(f"The Active network is {network.show_active()}")
    print("Deploying Mocks ...")
    if len(MockV3Aggregator) <= 0:
        MockV3Aggregator.deploy(
            DECIMALS, Web3.toWei(STARTING_PRICE, "ether"), {"from": get_account()}
        )
    print("Mocks Deployed!")
```
deploy.py 
```Python
from brownie import FundMe, MockV3Aggregator, network, config
from scripts.helpful_scripts import (
    get_account,
    deploy_mocks,
    LOCAL_BLOCKCHAIN_ENVIRONMENTS,
)


def deploy_fund_me():
    account = get_account()
    if network.show_active() not in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        price_feed_address = config["networks"][network.show_active()][
            "eth_usd_price_feed"
        ]
    else:
        deploy_mocks()
        price_feed_address = MockV3Aggregator[-1].address

    fund_me = FundMe.deploy(
        price_feed_address,
        {"from": account},
        publish_source=config["networks"][network.show_active()].get("verify"),
    )
    print(f"Contract deployed to {fund_me.address}")
    mock_aggregator = MockV3Aggregator.deploy(
        18, 2000000000000000000000, {"from": account}
    )
    price_feed_address = mock_aggregator.address
    print("Mock deployed!")


def main():

    deploy_fund_me()
```
brownie-config.yaml
```YAML
dependencies:
  # - <organisation/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
dotenv: .env
networks:
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  development:
    verify: False
  ganache-local:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
```
Does it have anything to do with when I added local ganache to the network list ?
with `brownie networks add Ethereum ganache-local host=http://127.0.0.1:7545 chainid=5777`
If yes how i can remove `ganache-local` from the network list to re add it.
