### DISCUSSION TITLE
Lesson 6 : ConnectionError

### DISCUSSION THREAD

**Discussion by wilonweb** [smartcontractkit/full-blockchain-solidity-course-py#1369] [Q&A] [answered]
Hello 
I launch the command `brownie run scripts/deploy.py --network ganache-local`
And i get that error 
`ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=7545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021B41627DF0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))`

I installed MySQL yesterday. The problem can from my previous SQL installation ? 
Or it is because i already deploy the contract ?

**Comment by wilonweb** [comment]
Update : 
I tried to delete and re-add ganache-local network with 
 `brownie networks delete ganache-local` and `brownie networks add Ethereum ganache-local host=http://127.0.0.1:7545 chainid=5777`
And now when i launch
`brownie run scripts/deploy.py --network ganache-local`
I get 

`raise ContractNotFound(f"No contract deployed at {address}")
ContractNotFound: No contract deployed at 0x955052702Ce443af7EA19488C852D84eBcf0Ae41
PS D:\Programmations\smartContract\brownie_fund_me> brownie networks add Ethereum ganache-local host=http://127.0.0.1:7545 chainid=5777`

**Comment by cromewar** [comment, marked as answer]
Hello @NinjaTurtles-cloud 

> I installed MySQL yesterday. The problem can from my previous SQL installation ?

This could be dangerous as some database servers also uses the same ports as ganache, so reinstalling was a good choice

> raise ContractNotFound(f"No contract deployed at {address}") ContractNotFound: No contract deployed at 0x955052702Ce443af7EA19488C852D84eBcf0Ae41 PS D:\Programmations\smartContract\brownie_fund_me> brownie networks add Ethereum ganache-local host=http://127.0.0.1:7545 chainid=5777

the contract not found could be due to a brownie-config.yaml error, on lesson 6 you use the price feed provided by chainlink, so you must put the address your that contract or deploy mocks instead.

**Comment by wilonweb** [comment]
Hello, 

When you say : 
`the contract not found could be due to a brownie-config.yaml error, on lesson 6 you use the price feed provided by chainlink, so you must put the address your that contract or deploy mocks instead.`
( I don't know how to quote an old post ) 

I didn't really understand what i have to do.  ( i still have the contractNotFoud )
`ContractNotFound: No contract deployed at 0x955052702Ce443af7EA19488C852D84eBcf0Ae41`

and this is my `brownie-config.yaml`
```YAML
dependencies:
  # - <organisation/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
dotenv: .env
networks:
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  development:
    verify: False
  ganache-local:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
```
`
I have to take the `eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"` address ? 
And if so where should i put it ?
