### DISCUSSION TITLE
Lesson 6 _Deploy error

### DISCUSSION THREAD

**Discussion by sako013** [smartcontractkit/full-blockchain-solidity-course-py#1468] [Q&A] [answered]
Hello
I launch the command brownie run scripts/deploy.py --network rinkeby
And i get this error

ValueError: constructor Sequence has incorrect length, expected 1 but got
 
I can read the account address but its not deploying!

**Comment by cromewar** [comment]
Hello @sako013 
This means your smart contract takes one parameter on it's constructor and your are not providing any on execution, but we will need more info on this, please give a check to #980  and reformulate your question.

**Reply by sako013** [reply]
Thank you for your respond,
here is my brownie-config.yaml

```YAML
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

dotenv : .env
wallets : 
  from_key : ${PRIVATE_KEY}
```
