### DISCUSSION TITLE
Lesson 7- Lottery.deploy() is not deploying in test

### DISCUSSION THREAD

**Discussion by sako013** [smartcontractkit/full-blockchain-solidity-course-py#1477] [General]
![erorr](https://user-images.githubusercontent.com/10506312/168168135-23e38c46-4ad7-4e55-8623-a9d0349a3939.png)

E   ImportError: cannot import name 'MockV3Aggregator' from 'brownie' (C:\Users\Python310\lib\site-packages\eth_brownie-1.18.1-py3.10.egg\brownie\__init__.py)
================================================== short test summary info =================================================== 
FAILED tests/test_lottery.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by sako013** [comment]
brownie-config.yaml


```YAML
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

networks:
  default: development
  mainnet-fork:
    eth_usd_price_feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'

        
dotenv : .env
wallets : 
  from_key : ${PRIVATE_KEY}
```
