### DISCUSSION TITLE
Mac M1 Issue  | Import Error & File Not Found Error

### DISCUSSION THREAD

**Discussion by michaelshimeles** [smartcontractkit/full-blockchain-solidity-course-py#1626] [Q&A] [answered]
I've been having issues with Import Parser Error and File Not Found Error and I can confidently say I believe the issue is my M1.

I spent the last few days trying out every solution but at the end of the day, importing chainlink and openzeppelin contracts have been impossible.

**Has anyone with a M1 figured out the solution? It's so hard going through the course without being able to test or compile?

Please help!**

<img width="1121" alt="Screen Shot 2022-08-03 at 2 59 54 PM" src="https://user-images.githubusercontent.com/69605071/182688226-9485601f-29e6-422c-8781-ebeaf2bf57ff.png">
<img width="1276" alt="Screen Shot 2022-08-03 at 3 00 01 PM" src="https://user-images.githubusercontent.com/69605071/182688230-f81228ac-126a-4d6c-bf5b-3c5d1d22329d.png">
being able to compile / test.

**Comment by cromewar** [comment, marked as answer]
Hello @michaelshimeles 
There are several reasons for this not to work, so please check the following:

- [ ] Check any mismatch on the open zeppelin packages on `brownie-config-yaml`.
- [ ] Check any version on your smart contracts, some contracts are not available on some OpenZeppelin versions.
- [ ] Delete `.brownie` folder on your home directory and try again.

I hope this info might help.

**Reply by michaelshimeles** [reply]
**Here's my code, I did everything you suggested, not sure if I'm missing something**

```Solidity
// SPDX-License-Identifier: MIT

pragma solidity ^0.6.6;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";

contract SimpleCollectible is ERC721 {
    uint256 public tokenCounter;

    constructor() public ERC721("Dogie", "DOG") {
        tokenCounter = 0;
    }

    function createCollectible(string memory tokenURI)
        public
        returns (uint256)
    {
        uint256 newTokenId = tokenCounter;
        _safeMint(msg.sender, newTokenId);
        _setTokenURI(newTokenId, tokenURI);
        tokenCounter = tokenCounter + 1;
        return newTokenId;
    }
}

```

brownie-cofig.yaml
```YAML
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env
```
