### DISCUSSION TITLE
Lesson 11: Verifying AdvancedCollectible Contract On Etherscan

### DISCUSSION THREAD

**Discussion by Niferu** [smartcontractkit/full-blockchain-solidity-course-py#1694] [Q&A] [answered]
Hello,

At around 10:50:00 and later on in course Patrick is showing verified contract details (his contract has been verified automatically somehow). In my case none of my contracts has been verified (I have already tried tons of times). I have also tried to manually publish and verify deployed contract but I keep getting error that it does not recognize my 2 imports of ERC721 and VRFConsumerBase. I have also tried to use following line of code in my deploy script:  `publish_source = config["networks"][network.show_active()].get("verify", False)`, but it throws below error:

![image](https://user-images.githubusercontent.com/110537615/189007209-3d247156-d6dd-4be9-b02d-a2aee8adb27d.png)

Error from etherscan manual verification:

![image](https://user-images.githubusercontent.com/110537615/189007796-b078cb4b-8be8-4dfc-9889-b06dcb3f8527.png)

Anyone can help me to solve this issue? I'm unable to see if my `tokenCounter` works properly.

**Comment by cromewar** [comment]
Hello @Neftyr 
The reason Patrick contracts get verified automatically is because the code is exactly the same as a previous contract. The reasons is because when a contract have the same code the bytecode will be also the same, so if a contract with the same bytecode was already verified the verification will pass automatically.

Regarding to your issue, please share the following:
Your brownie-config.yaml.

And remember to have setup the etherscan key on .env

**Reply by Niferu** [reply]
Hello @cromewar,

Thank you for your help. I have etherscan key added to my `.env`, please see below `brownie-config.yaml` code:

```yaml
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
networks:
  development:
    keyHash: '0x0476f9a745b61ea5c0ab224d3a6e4c99f0b02fce4da01143a4f70aa80ae76e8a'
    fee: 100_000_000_000_000_000 # 0.1
  goerli:
    vrf_coordinator: '0x2bce784e69d2Ff36c71edcB9F88358dB0DfB55b4'
    link_token: '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'
    keyHash: '0x0476f9a745b61ea5c0ab224d3a6e4c99f0b02fce4da01143a4f70aa80ae76e8a'
    fee: 100_000_000_000_000_000 # 0.1
    verify: True
  rinkeby:
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyHash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100_000_000_000_000_000 # 0.1
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
```
