### DISCUSSION TITLE
Lesson 6 FundMe I cannot get the contract

### DISCUSSION THREAD

**Discussion by fricpto** [smartcontractkit/full-blockchain-solidity-course-py#1819] [Q&A] [answered]
Hello, I have created a `__init__.py`,`brownie-config.yaml`,`deploy.py`,`helpful_scripts.py`,`.env`,`FundMe.sol` files and when I try to run 
brownie run scripts/deploy.py --network goerli I'll get this output:
<img width="545" alt="Screenshot 2023-01-01 233039" src="https://user-images.githubusercontent.com/100000316/210185113-f6b6a7c5-5c10-4c32-9ac9-dfb085879833.png">
and this is my deploy.py code:
```Python
from brownie import FundMe
from scripts.helpful_scripts import get_account



def deploy_fund_me():
    account = get_account()
    fund_me = FundMe.deploy({"from": account})
    print(f"Contract deployed to {fund_me.address}")


def main():
    deploy_fund_me

-this is my helpful_scripts.py code:
from brownie import config, network, accounts


def get_account():
    if network.show_active() == "development":
        return accounts[0]
    else:
        return accounts.add(config["wallets"]["from_key"])

```
-this is my brownie-config.yaml code:

```YAML
dependencies:
    - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
dotenv: .env
wallets:
from_keys: ${PRIVATE_KEY}
```

-this is my .env file:
export PRIVATE_KEY= 0xf1daaaaaaaaaaaaaaaaaaaaaa
export WEB3_INFURA_PROJECT_ID = bd89aaaaaaaaaaa
