### DISCUSSION TITLE
lesson 7: Brownie compile

### DISCUSSION THREAD

**Discussion by sundaepromix** [smartcontractkit/full-blockchain-solidity-course-py#1834] [Q&A] [answered]
**Brownie v1.19.3 - Python development framework for Ethereum**

1.23MiB [00:01, 661kiB/s] 
WARNING: Unable to compile smartcontractkit/chainlink-brownie-contracts@0.3.1 due to a IsADirectoryError - you may still be able to import sources from the package, but will be unable to load the package directly.

  File "brownie/_cli/__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "brownie/_cli/compile.py", line 50, in main
    proj = project.load()
  File "brownie/project/main.py", line 780, in load
    return Project(name, project_path)
  File "brownie/project/main.py", line 188, in __init__
    self.load()
  File "brownie/project/main.py", line 257, in load
    self._compile(changed, self._compiler_config, False)
  File "brownie/project/main.py", line 90, in _compile
    _install_dependencies(self._path)
  File "brownie/project/main.py", line 786, in _install_dependencies
    install_package(package_id)
  File "brownie/project/main.py", line 808, in install_package
    return _install_from_github(package_id)
  File "brownie/project/main.py", line 871, in _install_from_github
    download_url = _get_download_url_from_tag(org, repo, version, headers)
  File "brownie/project/main.py", line 955, in _get_download_url_from_tag
    raise ValueError(
ValueError: Invalid version for this package. Available versions are:
4.8.1, 4.8.0, 4.8.0-rc.2, 4.8.0-rc.1, 4.8.0-rc.0, 4.7.3, 4.7.2, 4.7.1, 4.7.0, 4.7.0-rc.0, 4.6.0, 4.6.0-rc.0, 4.5.0, 4.5.0-rc.0, 4.4.2, 4.4.1, 4.4.0, 4.4.0-rc.1, 4.4.0-rc.0, 4.3.3, 4.3.2, 4.3.1, 4.3.0, 4.3.0-rc.0, 4.2.0, 4.2.0-rc.0, 4.1.0, 4.1.0-rc.0, 4.0.0, 4.0.0-rc.0, 4.0.0-beta.1, 4.0.0-beta.0, 3.4.2, 3.4.2-solc-0.7, 3.4.1, 3.4.1-solc-0.7, 3.4.1-solc-0.7-2, 3.4.0, 3.4.0-solc-0.7, 3.4.0-rc.0, 3.3.0, 3.3.0-solc-0.7, 3.3.0-rc.2, 3.3.0-rc.1, 3.3.0-rc.0, 3.2.2-solc-0.7, 3.2.1-solc-0.7, 3.2.0, 3.2.0-rc.0, 3.1.0, 3.1.0-solc-0.7, 3.1.0-rc.0, 3.0.2, 3.0.1, 3.0.0, 3.0.0-rc.1, 3.0.0-rc.0, 3.0.0-beta.0, 2.5.1, 2.5.0, 2.5.0-rc.0, 2.4.0, 2.4.0-beta.2, 2.4.0-beta.1, 2.4.0-beta.0, 2.3.0, 2.3.0-rc.3, 2.3.0-rc.2, 2.3.0-rc.1, 2.3.0-rc.0, 2.2.0, 2.2.0-rc.1, 2.1.3, 2.1.2, 2.1.1, 2.1.0-rc.2, 2.1.0-rc.1, 2.0.1, 2.0.0, 2.0.0-rc.4, 2.0.0-rc.3, 2.0.0-rc.2, 2.0.0-rc.1, 1.12.0, 1.12.0-rc.2, 1.12.0-rc.1, 1.11.0, 1.11.0-rc.1, 1.10.0, 1.9.1, 1.9.0, 1.8.0, 1.7.0, 1.6.0, 1.5.0, 1.4.0, 1.3.0, 1.2.0, 1.1.0, 1.0.7

**Comment by sundaepromix** [comment]
brownie-config.yaml

```YAML
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0;
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin= OpenZeppelin/openzeppelin-contracts@3.4.0'
networks:
  mainnet-fork:
  eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
```
