### DISCUSSION TITLE
lesson 7: SmartContract Lottery

### DISCUSSION THREAD

**Discussion by sundaepromix** [smartcontractkit/full-blockchain-solidity-course-py#1836] [Q&A] [answered]
here is the error in my terminal

Running 'scripts/deploy_lottery.py::main'...
Transaction sent: 0xfd99566180954fef0805cea66c6a3011ca99d86475a901d34267d0eae2c109e3
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 0
  MockV3Aggregator.constructor confirmed   Block: 1   Gas used: 430659 (3.59%)
  MockV3Aggregator deployed at: 0x3194cBDC3dbcd3E11a07892e7bA5c3394048Cc87

Transaction sent: 0x8ef2772ab557cf6e7bb5088682c154788b79e379341c296acc3572470547e073
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 1
  LinkToken.constructor confirmed   Block: 2   Gas used: 669136 (5.58%)
  LinkToken deployed at: 0x602C71e4DAC47a042Ee7f46E0aee17F94A3bA0B6

Transaction sent: 0x737d009e9827546c81bb7567a7dd980f9b4c36ba10eae9579866d60c656851b7
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 2
  VRFCoordinatorMock.constructor confirmed   Block: 3   Gas used: 276395 (2.30%)
  VRFCoordinatorMock deployed at: 0xE7eD6747FaC5360f88a2EFC03E00d25789F69291

deployed!
  File "brownie/_cli/run.py", line 51, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 110, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/deploy_lottery.py", line 19, in main
    deploy_lottery()
  File "./scripts/deploy_lottery.py", line 8, in deploy_lottery
    get_contract("eth_usd_price_feed").address,
AttributeError: 'NoneType' object has no attribute 'address'
Terminating local RPC client...

**Comment by sundaepromix** [comment]
**deploy_lottery.py**

from scripts.helpful_scripts import get_account, get_contract
from brownie import Lottery, network, config


```Python
def deploy_lottery():
    account = get_account()
    lottery = Lottery.deploy(
        get_contract("eth_usd_price_feed").address,
        get_contract("vrf_coordinator").address,
        get_contract("link_token").address,
        config["networks"][network.show_active()]["fee"],
        config["networks"][network.show_active()]["keyhash"],
        {"from": account},
        publish_source=config["networks"][network.show_active()].get("verify", False),)
    print("Deployed lottery!")
    return lottery

def main():
    deploy_lottery()
```

**Comment by sundaepromix** [comment]
**brownie-config.yaml**


```YAML
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
networks:
  default: development
  development: 
    keyHash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
  goerli: 
    vrf_coordinator: "0x2bce784e69d2Ff36c71edcB9F88358dB0DfB55b4"
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    link_token: "0x326C977E6efc84E512bB9C30f76E30c160eD06FB"
    keyHash: "0x0476f9a745b61ea5c0ab224d3a6e4c99f0b02fce4da01143a4f70aa80ae76e8a"
    fee: 100000000000000000
    verify: True
  mainnet-fork:
   eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
   verify: False
wallets: 
  from key: $(PRIVATE_KEY)
```
