### DISCUSSION TITLE
ImportError: cannot import name 'MockV3Aggregator' from 'brownie'

### DISCUSSION THREAD

**Discussion by chioke07** [smartcontractkit/full-blockchain-solidity-course-py#1857] [Q&A] [answered]
<img width="1512" alt="Screenshot 2023-04-02 at 1 04 47 PM" src="https://user-images.githubusercontent.com/129320402/229343444-7545895f-5c64-4473-b6a8-00250ffe2819.png">

i got this error while following lesson 6 i have tried all possible means to fix it, please can someone help me out?

from brownie import FundMe, MockV3Aggregator, network, config
ImportError: cannot import name 'MockV3Aggregator' from 'brownie' (/Users/israel/.local/pipx/venvs/eth-brownie/lib/python3.9/site-packages/brownie/__init__.py)

**Comment by Niferu** [comment, marked as answer]
Hello @chioke07 

As I can see you do not even have `MockV3Aggregator` under your `contracts` -> `test` folder. It should be as below:

![image](https://user-images.githubusercontent.com/110537615/229509978-13755006-3128-48ba-9ac0-3a6c6a63532a.png)

Check your `brownie-config.yaml` also if it looks like this and if you have no typo there:

```yaml
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
```
