### DISCUSSION TITLE
Lesson 12: CompilerError

### DISCUSSION THREAD

**Discussion by toddabraham** [smartcontractkit/full-blockchain-solidity-course-py#195] [Q&A] [answered]
Getting the following error when compiling.....

```bash
CompilerError: solc returned the following errors:

ParserError: Source "@openzeppelin/contracts/access/Ownable.sol" not found: File outside of allowed directories.
 --> contracts/transparent_proxy/ProxyAdmin.sol:6:1:
  |
6 | import "@openzeppelin/contracts/access/Ownable.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


ParserError: Source "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol" not found: File outside of allowed directories.
 --> contracts/transparent_proxy/TransparentUpgradeableProxy.sol:5:1:
  |
5 | import "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";
```

Code snippets from ProxyAdmin.sol & TransparentUpgradeableProxy.sol....

```Python
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "./TransparentUpgradeableProxy.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
```

```Python
/ SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";
```

**Comment by cromewar** [comment, marked as answer]
Do not forget to set up your `brownie-config.yaml` and set the oppenzepelin replacement for the solc compiler, something like this:

```YAML
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
```

If no thing works you can always install the npm module for openzeppelin using:

`npm install @openzeppelin/contracts`
