### DISCUSSION TITLE
Lottery always returen to me winner is 0x0000000000000000000000000000000000000000

### DISCUSSION THREAD

**Discussion by mohzourob** [smartcontractkit/full-blockchain-solidity-course-py#271] [Q&A] [answered]
I have tried to increase wait time from 60 to 120 but always give me the same response 0x0000000000000000000000000000000000000000 ?? why ??

**Comment by cromewar** [comment]
Hey @dash7ou I had the same problem, this happens because brownie is not taking the correct account it should, I don't know how advanced you are on the lottery project but I have some suggestion for you:

1. Make sure your `get_account` function seems like this:


```Python
FORKED_LOCAL_ENVIRONMENTS = ["mainnet-fork", "mainnet-fork-fev"]
LOCAL_BLOCKCHAIN_ENVIRONMENTS = ["development", "ganache-local"]

def get_account(index=None, id=None):
    # for specific account into the ganache-cli testnet accounts
    if index:
        return accounts[index]
    # For specific account configured on brownie accounts
    if id:
        return accounts.load(id)
    if (
        network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS
        or network.show_active() in FORKED_LOCAL_ENVIRONMENTS
    ):
        # for any of the local or forked environemnts return the account with index zero
        return accounts[0]

    # Default option, load from config file

    return accounts.add(config["wallets"]["from_key"])

```
2. Make sure your `brownie-config.yaml` looks like this:

```YAML
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
dotenv: .env
networks:
  default: development
  development:
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000
  rinkeby:
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000
    verify: True
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
wallets:
  from_key: ${PRIVATE_KEY}
```
3. Your `end_lottery` should look like this:

``` Python
def end_lottery():
    account = get_account()
    lottery = Lottery[-1]
    # fund de contract and  end the lottery
    tx = fund_with_link(lottery.address)
    tx.wait(1)
    ending_transaction = lottery.endLottery({"from": account})
    ending_transaction.wait(1)
    time.sleep(60)
    print(f"{lottery.recentWinner()} is the winner!")
    print("Lottery ended successfully")
```

If you want to use your own test account don't forget to add `id=name-of-your-brownie-account` on each `get_account` call.

Finally, deleting the build folder and compiling again always helps.

Best regards.
