### DISCUSSION TITLE
aave_borrow.py - self._accounts[key] - list index out of range

### DISCUSSION THREAD

**Discussion by 8bcb** [smartcontractkit/full-blockchain-solidity-course-py#378] [Q&A] [answered]
Hey :) I came across following error when running cmd `brownie run scripts/aave_borrow.py --network kovan`
I guess it worked pretty fine until certain moment and right now accounts list seems to be empty

<img width="472" alt="Screenshot 2021-11-17 at 08 41 50" src="https://user-images.githubusercontent.com/22620416/142157145-baf5374d-2cc9-4bd6-9dae-ac3079f55110.png">

Here is my config
```YAML
dependencies:
    - aave/protocol-v2@1.0.1
    - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
    solc:
        remappings:
            - "@aave=aave/protocol-v2@1.0.1"
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
networks:
    mainnet-fork:
        lending_pool: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
        weth_token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
        dai_eth_price_feed: "0x773616E4d11A78F511299002da57A0a94577F1f4"
    kovan:
        weth_token: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
        lending_pool: "0x88757f2f99175387aB4C6a4b3067c77A695b0349"
        dai_eth_price_feed: "0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541"
dotenv: .env
wallets:
    from_key: ${PRIVATE_KEY}
```

and also regular get_account() function
```Python
def get_account():
    if (
        network.show_active() in LOCAL_ENVIRONMENTS
        or network.show_active() in LOCAL_FORK_ENVIRONMENTS
    ):
        return accounts[0]
    else:
        return accounts.add(config["wallets"]["from_key"])
```

Any idea what can be wrong?
