### DISCUSSION TITLE
Lesson 7: VRFConsumerBase.sol" not found

### DISCUSSION THREAD

**Discussion by programonauta** [smartcontractkit/full-blockchain-solidity-course-py#617] [Q&A] [answered]
Hi, following the tutorial at time 7:09 when compile the contract, I received the error:

```
$ brownie compile
Brownie v1.17.2 - Python development framework for Ethereum

Compiling contracts...
  Solc version: 0.6.12
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

contracts/lottery.sol:7:1: ParserError: Source "/home/ricardo/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.8/VRFConsumerBase.sol" not found: File not found.
import "@chainlink/contracts/src/v0.8/VRFConsumerBase.sol";
^---------------------------------------------------------^
```

I've checked out `brownie-config.yaml`

```YAML
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
networks:
  mainnet-fork: 
    ethUsdPriceFeed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
```

Why didn't brownie push the file `VRFConsumerBase.sol`?
