### DISCUSSION TITLE
Lesson 10: Gas estimation failed ERROR

### DISCUSSION THREAD

**Discussion by jacobbinnie** [smartcontractkit/full-blockchain-solidity-course-py#767] [Q&A] [answered]
Hey there,

Keep getting the following error when trying to deploy on the Kovan network. When testing on local Ganache everything works great. I wondered if it was a Eth balance issue so I got more than enough Kovan Eth from the faucet. Still getting the error and I've even gone as far as copying and pasting the code from the Github repository.

<img width="704" alt="Screen Shot 2022-01-13 at 1 02 45 PM" src="https://user-images.githubusercontent.com/83803154/149242180-a2b05424-7bdc-4a9d-bd70-bb29666a4545.png">

Here's my aave_borrow.py script:

```Python
from brownie import network, config, interface
from scripts.helpful_scripts import get_account
from scripts.get_weth import get_weth
from web3 import Web3

# 0.1
AMOUNT = Web3.toWei(0.1, "ether")


def main():
    account = get_account()
    erc20_address = config["networks"][network.show_active()]["weth_token"]
    if network.show_active() in ["mainnet-fork"]:
        get_weth()
    lending_pool = get_lending_pool()
    approve_tx = approve_erc20(AMOUNT, lending_pool.address, erc20_address, account)
    print("Depositing...")
    tx = lending_pool.deposit(
        erc20_address, AMOUNT, account.address, 0, {"from": account}
    )
    tx.wait(1)
    print("Deposited!")
    # ...how much?
    borrowable_eth, total_debt = get_borrowable_data(lending_pool, account)
    print("Let's borrow!")
    # DAI in terms of ETH
    dai_eth_price = get_asset_price(
        config["networks"][network.show_active()]["dai_eth_price_feed"]
    )
    amount_dai_to_borrow = (1 / dai_eth_price) * (borrowable_eth * 0.95)
    # borrowable_eth -> borrowable_dai * 95%\
    print(f"We are going to borrow {amount_dai_to_borrow} DAI")
    # Now we will borrow!
    dai_address = config["networks"][network.show_active()]["dai_token"]
    borrow_tx = lending_pool.borrow(
        dai_address,
        Web3.toWei(amount_dai_to_borrow, "ether"),
        1,
        0,
        account.address,
        {"from": account},
    )
    borrow_tx.wait(1)
    print("We borrowed some DAI!")
    get_borrowable_data(lending_pool, account)
    repay_all(AMOUNT, lending_pool, account)
    print(
        "You just deposited, borrowed, and repayed with Aave, Brownie, and Chainlink!"
    )


def repay_all(amount, lending_pool, account):
    approve_erc20(
        Web3.toWei(amount, "ether"),
        lending_pool,
        config["networks"][network.show_active()]["dai_token"],
        account,
    )
    repay_tx = lending_pool.repay(
        config["networks"][network.show_active()]["dai_token"],
        amount,
        1,
        account.address,
        {"from": account},
    )
    repay_tx.wait(1)
    print("Repaid!")


def get_asset_price(price_feed_address):
    dai_eth_price_feed = interface.AggregatorV3Interface(price_feed_address)
    latest_price = dai_eth_price_feed.latestRoundData()[1]
    converted_latest_price = Web3.fromWei(latest_price, "ether")
    print(f"The DAI/ETH price is {converted_latest_price}")
    return float(converted_latest_price)


def get_borrowable_data(lending_pool, account):
    (
        total_collateral_eth,
        total_debt_eth,
        available_borrow_eth,
        current_liquidation_threshold,
        ltv,
        health_factor,
    ) = lending_pool.getUserAccountData(account.address)
    available_borrow_eth = Web3.fromWei(available_borrow_eth, "ether")
    total_collateral_eth = Web3.fromWei(total_collateral_eth, "ether")
    total_debt_eth = Web3.fromWei(total_debt_eth, "ether")
    print(f"You have {total_collateral_eth} worth of ETH deposited.")
    print(f"You have {total_debt_eth} worth of ETH borrowed.")
    print(f"You can borrow {available_borrow_eth} worth of ETH.")
    return (float(available_borrow_eth), float(total_debt_eth))


def approve_erc20(amount, spender, erc20_address, account):
    print("Approving ERC20 token...")
    erc20 = interface.IERC20(erc20_address)
    tx = erc20.approve(spender, amount, {"from": account})
    tx.wait(1)
    print("Approved!")
    return tx


def get_lending_pool():
    lending_pool_addresses_provider = interface.ILendingPoolAddressesProvider(
        config["networks"][network.show_active()]["lending_pool_addresses_provider"]
    )
    lending_pool_address = lending_pool_addresses_provider.getLendingPool()
    lending_pool = interface.ILendingPool(lending_pool_address)
    return lending_pool
```

**Comment by cromewar** [comment, marked as answer]
Hello @jacobbins I tried to reproduce the error with not luck as is runs ok on my side, however the error catch my attention when saying is reverting because is getting None. This could be due to your account.

1. make sure your account is setup on `brownie-config.yaml` using:
```YAML
wallets:
  from_key: ${PRIVATE_KEY}
```
2. Give a check yo your helpful scripts and make sure is returning the correct account.
3. Make sure your private key is correctly imported from `.env`

**Reply by jacobbinnie** [reply]
Hey @cromewar, I really appreciate the response.

Looks as though I had all the right code in my brownie-config. However, some indentation was different from the public code on Github. After fixing it up everything worked great! Seems pretty picky haha!

Thanks!

**Reply by cromewar** [reply]
Well, I'm glad you managed to solve this.

**Comment by Verde888** [comment]
Hi Guys,
exactly the same problem here.

The code looks fine, I copied it from the repo...
The wallet is correct, in fact, the script works for borrowing – I can see on MetaMask that my wallet receives the aETH tokens and loses WETH tokens. 
But it never gets to print "We borrowed some DAI!" and everything that follows. Strange.

Hopefully we'll figure it out together.

**Reply by jacobbinnie** [reply]
Hey @Verde888 can you try copying all of this into your brownie-config?

```
dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'
dotenv: .env
networks:
  default: mainnet-fork
  kovan:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    lending_pool_addresses_provider: '0x88757f2f99175387ab4c6a4b3067c77a695b0349'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
    dai_token: '0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD'
  mainnet-fork:
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    lending_pool_addresses_provider: '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'
    dai_eth_price_feed: '0x773616E4d11A78F511299002da57A0a94577F1f4'
    dai_token: '0x6b175474e89094c44da98b954eedeac495271d0f'
wallets:
  from_key: ${PRIVATE_KEY}
```
