### DISCUSSION TITLE
Lesson 7: Brownie compile issue - Invalid version of this package

### DISCUSSION THREAD

**Discussion by AmiyoKC** [smartcontractkit/full-blockchain-solidity-course-py#931] [Q&A] [answered]
I'm trying to run brownie compile and am getting the error below. Been stuck with this for quite a few days. Am not sure what's going wrong. I read through other responses to a similar issue but wasn't quite able to fix this issue. It's not clear to me which package's version the error message below is talking about 

PS C:\Users\amiyo\demos\smartcontract-lottery> brownie compile

INFO: Could not find files for the given pattern(s).
Brownie v1.16.4 - Python development framework for Ethereum

  File "C:\Users\amiyo\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\_cli\__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "C:\Users\amiyo\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\_cli\compile.py", line 50, in main
    proj = project.load()
  File "C:\Users\amiyo\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\project\main.py", line 750, in load
    return Project(name, project_path)
  File "C:\Users\amiyo\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\project\main.py", line 182, in __init__
    self.load()
  File "C:\Users\amiyo\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\project\main.py", line 237, in load
    self._compile(changed, self._compiler_config, False)
  File "C:\Users\amiyo\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\project\main.py", line 89, in _compile
    _install_dependencies(self._path)
  File "C:\Users\amiyo\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\project\main.py", line 756, in _install_dependencies
    install_package(package_id)
  File "C:\Users\amiyo\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\project\main.py", line 778, in install_package
    return _install_from_github(package_id)
  File "C:\Users\amiyo\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\project\main.py", line 859, in _install_from_github
    raise ValueError(
ValueError: Invalid version for this package. Available versions are:
0.2.1, test0.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0, 0.3.1, 0.3.0, 0.2.2, 0.2.1, 0.2.0

**Comment by cromewar** [comment, marked as answer]
Hello @AmiyoKC this a problem due to the python version you are using, python 3.10 have been reported as not 100% compatible yet with some of web3 dependencies, I strongly suggest you to use python 3.8, and also on a virtualenv ;)

**Reply by AmiyoKC** [reply]
Hi @cromewar I installed venv and installed python 3.8.9. In the virtual env i had to reinstall brownie. I also changed the python interpreter from command palette to Python 3.8.9. Needed to also make a change to pyenv.cfg as that was still pointing to Python 3.10.

Unfortunately after doing all this I'm still getting this error message below when I run brownie compile



![Brownie_Compile error](https://user-images.githubusercontent.com/28237671/152450371-bfdea7df-f7b3-4b23-9dae-91a862fc0cd9.jpg)

**Reply by cromewar** [reply]
If I have to guess I would say the problem is most likely on your `brownie-config.yaml`, could you share it here please?

**Reply by AmiyoKC** [reply]
sure. cut-pasting in it's entirety below.

also note this whole thing was working before -- i had compiled it, was running tests etc. They suddenly (mysteriously) i started getting these errors. 



---------------------------------------------

```YAML
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@01.3.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.3.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
    version: 'v.0.8.7'
dotenv: .env
networks:  
  default: development
  development:
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 10000000000000000
  rinkeby:
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 10000000000000000
    verify: True
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
wallets:
  from_key: ${PRIVATE_KEY}
```

**Reply by AmiyoKC** [reply]
also I've been tinkering with solidity version and version of the contracts and interfaces i'm importing in Lottery.sol. currently I have this below with pragma solidity ^0.8.7;

I've spent a lot of time trying various things but nothings working.

import "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@chainlink/contracts/src/v0.8/VRFConsumerBase.sol";

**Reply by freddie71010** [reply]
@AmiyoKC  can you use markdown in ur posts? makes reading the code a lot more readable. Use three ` before and after your code.
```
code goes here
```
<img width="88" alt="image" src="https://user-images.githubusercontent.com/19274376/152585775-74b8a43f-4d46-40c8-881c-0158bf644ac5.png">

**Reply by AmiyoKC** [reply]
sorry about that. see below:

```
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.3.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.3.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
    version: 'v.0.8.7'
dotenv: .env
networks:  
  default: development
  development:
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 10000000000000000
  rinkeby:
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 10000000000000000
    verify: True
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
wallets:
  from_key: ${PRIVATE_KEY}
```
