### DISCUSSION TITLE
How to ask questions in the repository.

### DISCUSSION THREAD

**Discussion by cromewar** [smartcontractkit/full-blockchain-solidity-course-py#980] [General]
Hello everyone, I hope you are enjoying the course contents so far, Patrick made a lot of effort to get this done.

If you are facing some problems or issues on your journey, this is the best place to find help from another students, so you can freely make any questions you have here. 

However, the better the questions the better the answers. so here you have a guide line to post your questions here:
Note. Thanks to @n4n0b1t3 for the hint.

1. Create a describing tittle of the error include the lesson number on it and the time stamp of the video if possible
2. Describe what is your issue and what you have tried but didn't work so far to solve the issue.
3. Post your source code (line numbers would be great), don't forget about using the formatting your code via triple back ticks (`)!.
4. Post your terminal error message.
5. share your brownie-config.yaml.

Update: Thanks to @Dave777  and @freddie71010 for the tips

**Comment by Dave777** [comment]
Starting the Question with "Lesson ( insert number )"  is also helpful to know where in the course it relates.

**Comment by freddie71010** [comment]
Also, don't forget about using the formatting your code via triple back ticks (`)!

**Reply by n4n0b1t3** [reply]
yes, in general, make use of the editor formatting features.

**Reply by n4n0b1t3** [reply]
Even though I suggested it, after trying to support a request, where the code had line numbers, I noticed that this makes it very difficult to copy the code for testing it myself. I would suggest, removing line numbers from the best practice part. However, what is very common and makes it often impossible to support is the wrong use of the code format. For example, just small changes in the config.yaml format will cause errors. If someone posts with single backticks it will look like this:


> `dependencies:
>   # - <organisation/repo>@<version> brownie can download directly from GitHub with this info
>   - smartcontractkit/chainlink-brownie-contracts@0.3.0
> compiler:
>   solc:
>     remappings:
>       - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0'
> wallets:
>   from_key: ${PRIVATE_KEY}
> dotenv: .env`
> 

Instead of this
```
dependencies:
  # - <organisation/repo>@<version> brownie can download directly from GitHub with this info
  - smartcontractkit/chainlink-brownie-contracts@0.3.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0'
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env
```

The difference is, in the first example I used the code format button <> first, in the second example I pasted my code first, selected it and then pressed to code format button <>. Only the second format helps us to see if there are formatting errors or not.
