### DISCUSSION TITLE
Lesson 7 - Cannot import 'MockV3Aggregator' from 'brownie'  Error ?

### DISCUSSION THREAD

**Discussion by Dave777** [smartcontractkit/full-blockchain-solidity-course-py#991] [Q&A] [answered]
Hi,

I am getting this frustrating error when running "brownie run scripts/deploy_lottery.py"

Error is:
ImportError: cannot import name 'MockV3Aggregator' from 'brownie' (C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\__init__.py)
Terminating local RPC client..

Here is a screen shot showing the file structure and the helpful_scripts file

![Lesson7_001](https://user-images.githubusercontent.com/1362368/153028247-99b2a90d-7b62-4337-87df-197246447107.png)

Here is the  deploy_lottery.py

```
from scripts.helpful_scripts import get_account, get_contract, fund_with_link
from brownie import Lottery, network, config
import time


def deploy_lottery():
    account = get_account()
    lottery = Lottery.deploy(
        get_contract("eth_usd_price_feed").address,
        get_contract("vrf_coordinator").address,
        get_contract("link_token").address,
        config["networks"][network.show_active()]["fee"],
        config["networks"][network.show_active()]["keyhash"],
        {"from": account},
        publish_source=config["networks"][network.show_active()].get("verify", False),
    )
    print("Deployed Lottery !!")
    return lottery


def start_lottery():
    account = get_account()
    lottery = Lottery[-1]
    startLot_tx = lottery.startLot({"from": account})
    startLot_tx.wait(1)
    print("Lottery Started !!")


def enter_lottery():
    account = get_account()
    lottery = Lottery[-1]
    value = lottery.getEntranceFee() + 10000000
    tx = lottery.enter({"from": account, "value": value})
    tx.wait(1)
    print("You Have Entered the Lottery !!")


def end_lottery():
    account = get_account()
    lottery = Lottery[-1]
    # Fund the contract to be able to use the external random function
    txn = fund_with_link(lottery.address)
    txn.wait(1)
    endLot_tx = lottery.endLot({"from": account})
    endLot_tx.wait(1)
    time.sleep(60)
    print(f"{lottery.recentWinner()} is the new Winner !!")


def main():
    deploy_lottery()
    start_lottery()
    enter_lottery()
    end_lottery()

```

and the helpful_scripts.py

```
from brownie import (
    accounts,
    network,
    config,
    MockV3Aggregator,
    VRFCoordinatorMock,
    LinkToken,
    Contract,
)

LOCAL_FORKED_ENVS = ["mainnet-fork", "mainnet-fork-dev"]
LOCAL_BC_ENV = ["development", "ganache-local"]
DECIMALS = 10
STARTING_PRICE = 200000000000


def get_account(index=None, id=None):
    # 3 methods
    # 1. accounts[0]
    # 2. accounts.add("env")
    # 3. accounts.load("id")

    if index:
        return accounts[index]
    if id:
        return accounts.load(id)
    if (
        network.show_active() in LOCAL_BC_ENV
        or network.show_active() in LOCAL_FORKED_ENVS
    ):
        return accounts[0]
    return accounts.add(config["wallets"]["from_key"])


contract_to_mock = {
    "eth_usd_price_feed": MockV3Aggregator,
    "vrf_coordinator": VRFCoordinatorMock,
    "link_token": LinkToken,
}


def get_contract(contract_name):
    """
    This function will grab the contract addresses from the brownie
    config if defined, otherwise it will deploy a mock version of the
    contract and return that mock contract.

        args:
        contract_name (string)

        returns:
        brownie.network.contract.ProjectContract:
        The most recently deployed version of this contract.

    """
    contract_type = contract_to_mock[contract_name]
    if network.show_active() in LOCAL_BC_ENV:
        if len(contract_type) <= 0:
            deploy_mocks()
        contract = contract_type[-1]
    else:
        contract_address = config["networks"][network.show_active()][contract_name]
        contract = Contract.from_abi(
            contract_type._name, contract_address, contract_type.abi
        )
    return contract


def deploy_mocks(decimals=DECIMALS, start_price=STARTING_PRICE):
    account = get_account()
    MockV3Aggregator.deploy(decimals, start_price, {"from": get_account()})
    link_token = LinkToken.deploy({"from": account})
    VRFCoordinatorMock.deploy(link_token.address, {"from": account})
    print("Mocks Deployed")


def fund_with_link(
    contract_address, account=None, link_token=None, amount=100000000000000000
):
    account = account if account else get_account()
    link_token = link_token if link_token else get_contract("link_token")
    tx = link_token.transfer(contract_address, amount, {"from": account})
    tx.wait(1)
    print("Funded Contract")
    return tx

```

and my brownie-config.yaml

```
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings: "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"

dotenv: .env

networks:
  default: development
  development:
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
  rinkeby:
    vrf_coordinator: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
    verify: True
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
wallets:
  from_key: ${PRIVATE_KEY}

```

I have these under the tests sub-dir - is that correct ?
 LinkToken.sol
 MockV3Aggregator.sol
 VRFCoordinatorMock,sol
 test_lottery.py

Hope someone can spot my mistake.

Many thanks.
