### ISSUE TITLE
Lesson 6: Not getting error when I forked and connect to mainnet network

### ISSUE THREAD

**Issue by shashankvivek** [smartcontractkit/full-blockchain-solidity-course-py#1307]
I am referring to [the codecamp video here](https://youtu.be/M576WGiDBdQ?t=21449) and I just started forking the mainnet. The weird thing is that I was expecting an error such as 

![image](https://user-images.githubusercontent.com/13137425/159140529-7030da5c-5aed-4423-8cdf-3550388e02b8.png)

but my contract is getting deployed every time I run, ` brownie run .\scripts\deploy.py --network mainnet-fork`

**brownie-config.yaml**

```
dependencies:
  #- <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
networks:
  # with --network with no network name , falls back to default "development" network
  # default: development
  kovan:
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    verify: True
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
```

what mistake am I doing? Please guide me through this silly mistake of mine.
