### ISSUE TITLE
Lesson 6:  Test using mainnet-fork-dev giving error. 

### ISSUE THREAD

**Issue by shashankvivek** [smartcontractkit/full-blockchain-solidity-course-py#1310]
when I run `brownie test --network mainnet-fork-dev` . I am getting below error:

![image](https://user-images.githubusercontent.com/13137425/159164411-d079ff34-b3f7-4978-b057-a462e6eb5a7b.png)

What is the reason? I am not able to understand the exact issue based on this message.  The test works fine if I run `brownie test` i.e. development env

**Comment by shashankvivek** [comment]
@cromewar : Can you please help me through this :(  What am I missing?

**Comment by cromewar** [comment]
Hello @shashankvivek 
I'll need more info on this, seems your `getEntraceFee` is reverting the transaction. So, please share the following information:
1. What is the output at deploying on development?.
2. The `brownie-config.yaml`.
3. The code of your test script.

**Comment by shashankvivek** [comment]
Hi @cromewar ,

1. For Lesson 7, I am at the beginning where there are no `deploy.py` script yet. I have created the contract and then created the mainnet-fork with API key and then running tests. 

Here is

**brownie-config.yaml**

```
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
networks:
  mainnet-fork:
    eth_use_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
```

**test_lottery.py**

```
# 1 USD => 0.017 ETH
# 170000000000000000
from brownie import Lottery, accounts,network,config
from web3 import Web3

def test_get_entrance_fee():
    account = accounts[0]
    lottery = Lottery.deploy(
        config["networks"][network.show_active()]["eth_use_price_feed"],
        {"from": account}
    )
    print(lottery.getEntranceFee())
    assert lottery.getEntranceFee() > 160000000000000000
    assert lottery.getEntranceFee() > Web3.toWei(0.016,"ether")
    assert lottery.getEntranceFee() < Web3.toWei(0.022,"ether")
```
