### ISSUE TITLE
Lesson 6: Able to add mainnet-fork-dev with alchemy key & subsequent network requests 

### ISSUE THREAD

**Issue by GratefulDave** [smartcontractkit/full-blockchain-solidity-course-py#1528]
I am following along at 6:02 of the lesson. 

**Expected Behavior**
I add mainnet-fork-dev as a network and run `brownie run scripts/deploy.py --network mainnet-fork-dev`. I am using placeholders instead of the API Token for security reasons and the proper API token is displayed on my local machine. I received the following response:
```(venv) ➜  brownie_fund_me2 brownie networks add development mainnet-fork-dev cmd=ganache-cli host=http://127.0.0.1 fork=https://eth-mainnet.alchemyapi.io/v2/$WEB3_ALCHEMY_PROJECT_ID accounts=10 mnemonic=brownie port=8545
Brownie v1.18.1 - Python development framework for Ethereum

SUCCESS: A new network 'mainnet-fork-dev' has been added
  └─mainnet-fork-dev
    ├─id: mainnet-fork-dev
    ├─cmd: ganache-cli
    ├─cmd_settings: {'fork': 'https://eth-mainnet.alchemyapi.io/v2/$WEB3_ALCHEMY_PROJECT_ID', 'accounts': 10, 'mnemonic': 'brownie', 'port': 8545}
    └─host: http://127.0.0.1
```
After running `brownie run scripts/deploy.py --network mainnet-fork-dev` I expected to see the ganache-cli launching as in the tutorial `Launching . . . "ganache-cli --accounts=10 --fork alchemy_api_url`, etc, and see the corresponding API activity in the Alchemy API dashboard. There is no activity in the Alchemy dashboard.

**Current Behavior**
I receive the same response when adding mainnet-fork-dev and running deploy.py on mainnet-fork-dev, but do not see the proper fork being used as in the Expected Behavior:
```
Brownie v1.18.1 - Python development framework for Ethereum
Compiling contracts...
  Solc version: 0.6.6
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
Generating build data...
 - smartcontractkit/chainlink-brownie-contracts@1.1.1/AggregatorInterface
 - smartcontractkit/chainlink-brownie-contracts@1.1.1/AggregatorV2V3Interface
 - smartcontractkit/chainlink-brownie-contracts@1.1.1/AggregatorV3Interface
 - smartcontractkit/chainlink-brownie-contracts@1.1.1/SafeMathChainlink
 - FundMe
 - MockV3Aggregator

BrownieFundMe2Project is the active project.
**This is where ganache-cli cmd should have been executed . . .***
Attached to local RPC client listening at '127.0.0.1:8545'...

Running 'scripts/deploy.py::main'...
Account: 0xfD87695e09986290D9F801A7087FC9313b24a9aB
Transaction sent: 0x490b8221fa13a48403b6fd2c9952a67d03e70fa45923017bced4acc1a3efa5da
  Gas price: 0.0 gwei   Gas limit: 6721975   Nonce: 0
  FundMe.constructor confirmed   Block: 1   Gas used: 407025 (6.06%)
  FundMe deployed at: 0xf984eF9028175F5AE5729e13832A8bF2DBeb45A9

Contract deployed at 0xf984eF9028175F5AE5729e13832A8bF2DBeb45A9
```
**Steps to Reproduce & Troubleshooting?**:

1. I delete my build folder and start with a fresh instance of ganache UI.
2. I add mainnet-fork-dev originally using the original HTTPS URL, but am using a placeholder here instead of disclosing my WEB3_ALCHEMY_PROJECT_ID: `brownie networks add development mainnet-fork-dev cmd=ganache-cli host=http://127.0.0.1 fork=https://eth-mainnet.alchemyapi.io/v2/$WEB3_ALCHEMY_PROJECT_ID accounts=10 mnemonic=brownie port=8545`.
3. I delete mainnet-fork.
4. I used the **actual** Alchemy API URL, but am not disclosing it for security purposes. The 'fork' key's field does display the proper Alchemy API Token in the response. 
5.  I tried adding alchemy as a provider and then setting that provider as described in the Brownies [Using a Hosted Node Provider](https://eth-brownie.readthedocs.io/en/stable/network-management.html#using-a-hosted-node-providers) documentation.
2. I tried deleting mainnet-fork-dev, added export WEB3_ALCHEMY_PROJECT_ID='{{Alchemy_ID}}' to my dotEnv file, and added the forked URL using the HTTPS URL with a $WEB3_ALCHEMY_PrOJECT ID. The response was the same as the one shown in the steps to reproduce. 

** Environment **
Mac Silicon
macOS Monterey 12.4
Python 3.8.9
Brownie 1.18.1
Node 18.1.0
Npm 8.8.8
Brownie-Config.Yaml:

```
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    version: 0.6.6
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
```
I have been able to follow through with the video until then and everything worked properly. I am using the same
