### ISSUE TITLE
Aave lesson: Final argument must be a dict of transaction parameters that includes a `from` field specifying the sender of the transaction

### ISSUE THREAD

**Issue by kjones86** [smartcontractkit/full-blockchain-solidity-course-py#1531]
I've tried deploying on both RInkeby and Kovan and received the same error: Here is my code. 

get_weth.py 

```Python
from scripts.helpful_scripts import get_account
from brownie import interface, config, network



def main():
    get_weth()


def get_weth():
    """
    Mints WETH by depositing ETH.
    """
    account = get_account
    weth = interface.IWeth(config["networks"][network.show_active()]["weth_token"])
    tx = weth.deposit()({"from": account, "value": 0.1 * 10 ** 18})
    print("Received 0.1 WETH")
    return tx`
```
    
    Here is my helpful scripts`from brownie import accounts, network, config
from dotenv import load_dotenv

```Python
LOCAL_BLOCKCHAIN_ENVIRONMENTS = ["development", "ganache-local", "mainnet-fork"]


def get_account(index=None, id=None):
    if index:
        return accounts[index]
    if network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        return accounts[0]
    if id:
        return accounts.load(id)
    if network.show_active() in config["networks"]:
        return accounts.add(config["wallets"]["from_key"])
    return None`
```

and here is my config file `dependencies: 
 ```YAML
- aave/protocol-v2@1.0.1
compiler: 
  solc:
    remappings:
     - '@aave=aave/protocol-v2@1.0.1'
dotenv: .env
networks:
  kovan:
    weth_token: '0xd0A1E359811322d97991E03f863a0C30C2cF029C'
  mainnet-fork:
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
wallets: 
  from_key: ${PRIVATE_KEY}`
```
