### ISSUE TITLE
Chapter 6: Brownie Fund Me 

### ISSUE THREAD

**Issue by sarojsaroj** [smartcontractkit/full-blockchain-solidity-course-py#219]
Error message on import statement
**Source "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol" not found: File import callback not supported**

```

// SPDX-License-Identifier: MIT

pragma solidity ^0.6.6;

import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
```

![Screenshot (61)](https://user-images.githubusercontent.com/46487143/137855064-297e696b-47cd-495f-9e9c-eee20187de22.png)

Dependencies  (brownie-config.yaml)
```
-dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
```
