### ISSUE TITLE
Lesson 6 - Status 401 when getting package versions from Github

### ISSUE THREAD

**Issue by redount2k9** [smartcontractkit/full-blockchain-solidity-course-py#432]
brownie-config.yaml
```
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
```
Error stack:
<img width="621" alt="Screen Shot 2021-11-24 at 6 49 37 PM" src="https://user-images.githubusercontent.com/13453590/143280734-73360a28-44a6-4468-95ae-fdd1733d2d49.png">

Any idea what might be causing this?
Thank you.
