### ISSUE TITLE
Lesson 10: No contract deployed

### ISSUE THREAD

**Issue by vlasebian** [smartcontractkit/full-blockchain-solidity-course-py#619]
Hello!

First of all, thank you for providing such a great course on smart contracts!

I am stuck at lesson 10 while trying to get some WETH. I believe it may be something related to how I forked the mainnet, but I couldn't solve the issue.

This is the error that I get when i run `brownie run scripts/aave_borrow.py`:
```
ContractNotFound: No contract deployed at 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
```

This is how I added the mainnet-fork to brownie networks:
```bash
brownie networks add development mainnet-fork cmd=ganache-cli host=http://127.0.0.1 fork=https://eth-mainnet.alchemyapi.io/v2/<KEY> accounts=10 mnemonic=brownie port=8545
```

This is my code:

```py
# get_weth.py
from brownie import interface, network, config
from scripts.util import get_account


def get_weth():
    """
    Mints WETH by depositing ETH.
    """

    account = get_account()
    weth = interface.IWeth(config["networks"][network.show_active()]["weth_token"])
    tx = weth.deposit({"from": account, "value": 0.1 * 10 ** 18})
    tx.wait(1)
    print("Received 0.1 WETH.")


def main():
    get_weth()
```

```py
# aave_borrow.py
from brownie import network, config
from scripts.util import get_account
from scripts.get_weth import get_weth


def main():
    account = get_account()
    erc20_address = config["networks"][network.show_active()]["weth_token"]
    if network.show_active() in ["mainnet-fork"]:
        get_weth()
```

``` py
# util.py (this is helper_scripts.py, I renamed it)
from brownie import accounts, config, network

LOCAL_BLOCKCHAIN_ENVIRONMENTS = [
    "development",
    "ganache",
    "ganache-local",
    "mainnet-fork",
]


def get_account(index=None, id=None):
    if index:
        return accounts[index]

    if network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        return accounts[0]

    if id:
        return accounts.load(id)

    if network.show_active() in config["networks"]:
        return accounts.add(config["wallets"]["from_key"])

    return None
```

```yaml
# brownie-config.yml
networks:
  default: mainnet-fork
  development:
    verify: False
  kovan:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c' 
    verify: True
  mainnet-fork:
    weth_token: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
    verify: True

wallets:
  from_key: ${PRIVATE_KEY}

dotenv: .env
```

What am I doing wrong here?

Thanks,
Vlad
